global:
  scrape_interval: 15s

scrape_configs:
  - job_name: my-node-exporter
    static_configs:
      - targets: ['localhost:9100'] # Windows / Mac hosts use ['host.docker.internal:9100'] | Linux can use <container name>:<host binded port>
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090'] # Assuming Prometheus is also running in a container
  - job_name: flask-app
    static_configs:
      - targets: [':5001']