global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: "1m"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ubuntu'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'python-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:5001']